### ISSUE TITLE
[Request] Can we get free credit if we wish to execute large batch of evaluations on VIBE-Eval?

### ISSUE THREAD

**Issue by Luodian** [reka-ai/reka-vibe-eval#5]
We are executing model evaluation on VIBE-Eval, but found that it consumes around 5 USD (rough estimation) per evaluations. It's a little bit expensive compared with other evals using GPT4V/o.

Just wondering if there a giving away plan or something? like 100 USD credit, and require the author to cite or promote Reka AI product.

**Comment by prazek** [comment]
Hi,
yes we do offer credits for running vibe eval. I sent credits link on your email.
No strings attached, so there is no need to promote us, but ofc citations for vibe-eval and tech report are welcome :)

**Comment by Luodian** [comment]
Pretty much thanks!
