### ISSUE TITLE
[Problem&Request]

### ISSUE THREAD

**Issue by URRealHero** [reka-ai/reka-vibe-eval#6]
Thanks for this great benchmark, I'm now testing it on my multi-agent system. However, when evaluation, Error `Hit error TypeError("'module' object is not callable"). Attempt 1 of 10.` occured. I didn't modify anything in `evaluate.py` and thought it might be reka api's problems. If you have any solution to these, please let me know.
What's more, since, there will be a large amount of testing, is there any credit for GPT4o as an evaluator we can have? I'm really glad and thankful for this benchmark and looking forward to your reply.

**Comment by URRealHero** [comment]
I think it's because no chat in reka modules?

**Comment by URRealHero** [comment]
I think there is sth wrong with reka.chat, and I'm wondering how to use gpt4o as a judge >_<

**Comment by matthen** [comment]
Thanks for the issue!

I think the problem is that this code assumes v1 of our python sdk, and is not compatible with v2. https://github.com/reka-ai/reka-vibe-eval/pull/7 should fix the problem, and you can run `pip install reka-api==1.0.6` in your environment to hopefully fix it too.

**Comment by URRealHero** [comment]
> code assumes v1 of our python sdk, and is not compatible wi

Thx a lot! Sorry to bother you, but could you teach me how to use gpt4o as a judge? Should I write a new script for that?

**Comment by URRealHero** [comment]
Am I able to get some credits? Since I'm testing it with a lot of mllms.

**Comment by matthen** [comment]
No problem! Yes, I'm afraid we do not provide code for that, so you would need to adapt `evaluate.py` yourself.

You could edit these lines to call a different model: https://github.com/reka-ai/reka-vibe-eval/blob/93ecd92fec87ebda5263affba744df40cc233609/evaluate.py#L152C5-L158C14

**Comment by URRealHero** [comment]
Sure! I just emailed u
